
language: perl

perl:
  - "5.8"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - tidy

install:
  - . ./tools/ci/install.sh

before_script: []

script:
  - . ./tools/ci/build.sh

env:
  global:
    - CS=dark
    - DEP_PREFIX=$HOME/.local
    - PATH=$PATH:$DEP_PREFIX/bin:$PREFIX/bin
    - Build_Deps_Default_Paths=1
  matrix:
    - ENV= PREFIX=
    #- ENV=production PREFIX=/usr/local

branches:
  not:
    - master

notifications:
  email:
    on_success: never

