
language: perl

perl:
  - "5.24"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - tidy

#pre_install:
#  - . ./tools/ci/init.sh

install:
  - . ./tools/ci/install.sh

#before_script:
#  - . ./tools/ci/check.sh

script:
  - . ./tools/ci/build.sh
#  - . ./tools/ci/test.sh

env:
  global:
    - CS=dark
    - DEP_PREFIX=$HOME/.local
    - PATH=$PATH:$DEP_PREFIX/bin:$PREFIX/bin
    - Build_Deps_Default_Paths=1
  matrix:
    - ENV= PREFIX=
    #- ENV=production PREFIX=/usr/local

branches:
  not:
    - master

notifications:
  email:
    on_success: never

# Id: bookmarklet/0.1.1-dev .travis.yml
