
language:

install:
  - ./install-dependencies.sh

before_script:
  - "export PATH=$PATH:$PREFIX/bin"

script: make

branches:
  not:
    - master

env:
  global:
    - Build_Deps_Default_Paths=1
  matrix:
    #- ENV= CS=dark PREFIX=.
    - ENV= CS=dark PREFIX=$HOME/.local
    #- ENV=production CS=dark PREFIX=/usr/local

