
language: perl

perl:
  - "5.8"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - tidy

install:
  - PREFIX=$DEP_PREFIX ./install-dependencies.sh all
  - cpanm -h
  - cpanm --install URI::Escape

before_script: []

script: make

branches:
  not:
    - master

env:
  global:
    - DEP_PREFIX=$HOME/.local
    - PATH=$PATH:$DEP_PREFIX/bin:$PREFIX/bin
    - Build_Deps_Default_Paths=1
  matrix:
    #- ENV= CS=dark PREFIX=.
    - ENV= CS=dark PREFIX=
    #- ENV=production CS=dark PREFIX=/usr/local

