# git-versioning main: bookmarklet

- type: application/x-project-mpe
  main: bookmarklet
  name: bookmarklet
  id: bookmarklet

  version: 0.1.1-dev # bookmarklet
  environments:
    - development

  scripts:
    init:
    - . ./tools/ci/install.sh
    build: "make all build"

  pd-meta:
    run:
      tags-scm-sh: "g_f='XXX\\|FIXME\\|TODO';git ls-files|while read f;do grep -n $g_f $f|grep -v 'task.*ignore'|sed 's#^#'\"$f\"'#';done" # tasks:ignore
    test: "make test"
    check: ":vchk make"
    build: "make all build"

